---
- hosts: all
  become: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: apache2 listen on port 8080
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8080" state=present
      notify:
        - restart apache2

    - name: apache2 virtualhost on port 8080
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8080>" state=present
      notify:
        - restart apache2

    - name: Remove index.html
      file:
        path: "/var/www/html/index.html"
        state: absent

    - name: Create Index.html
      copy:
        dest: "/var/www/html/index.html"
        content: |
          <h1> Testing Jenkins </h1>

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
